# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

name: Barog - Barry Ridge's Blog
email: barry.ridge@gmail.com
description: > # this means to ignore newlines until "url:"
  Learnings on learning machines; ramblings on rambling leanings.

url: "https://barryridge.github.io" # the base hostname & protocol for your site
domain_name: "https://www.barog.net"
baseurl: ""  # the subpath of your site, e.g. /blog/

# Social
github_username: barryridge # put your github username
twitter_username: barryridge # put your twitter username
linkedin_username: barry-ridge # put your linkedin username
scholar_authorid: oScEUMkAAAAJ # put your google scholar author id
contact_note: >
  I'm probably best contacted by e-mail.

# Footer text
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

# Blog
blog_name: barog
blog_description: learnings on learning machines<br>ramblings on rambling leanings

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
#   poetry:
#     output: true
#     permalink: /poetry/:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Ridge

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  repository: /papers/

# Gravatar
author:

  email: barry.ridge@gmail.com

# -----------------------------------------------------------------------------
# Other advanced settings (don't touch if you are not sure)
# -----------------------------------------------------------------------------
fontawesome_version: "4.6.3"
jquery_version: "1.12.4"
katex_version: "0.6.0"

# -----------------------------------------------------------------------------
# Turn off remote jekyll processing on Github
# -----------------------------------------------------------------------------
# include:
#   - ".nojekyll"


# -----------------------------------------------------------------------------
# Exclude bower components from build
# -----------------------------------------------------------------------------
exclude:
  - "bower_components"
  - "bower.json"

# -----------------------------------------------------------------------------
# Exclude npm components from build
# -----------------------------------------------------------------------------
exclude:
  - "node_modules"
  - "package.json"

# -----------------------------------------------------------------------------
# Exclude grunt components from build
# -----------------------------------------------------------------------------
exclude:
  - "Gruntfile.js"
